### ISSUE TITLE
Duplicate class creation

### ISSUE THREAD

**Issue by tsouza** [xvik/guice-persist-orient#4]
I've setup a simple example. 

Package "model" contains VertexA and VertexB, both annotated with "VertexType".
Guice module installs OrientModule and PackageSchemeModule configured to scan package "model".

After starting PersistService I get the following exception:
```

Caused by: com.orientechnologies.orient.core.exception.OSchemaException: Class VertexA already exists in current database
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.doCreateClass(OSchemaShared.java:906)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:363)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:111)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateClass.execute(OCommandExecutorSQLCreateClass.java:144)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1189)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1178)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

I'm using guice-persist-orient 3.0.0 with OrientDB v2.0.8 (local dependency) connected to a remote OrientDB v2.0.7 with a newly created database.

After doing a simple analysis it seems that the problem is with VertexTypeExtension, shouldn't it be implemented with "afterRegistration" instead of "beforeRegistration"?

**Comment by xvik** [comment]
Thank you for this bug! 
You forced me to write remote connection tests and I found a couple of new bugs.

Implementing vertex schema extension logic in before or after phase is a matter of taste. 
I prefer to fail early, so for me before is better. 
Overall, many parts of the library are plugins, so people could simply replace any extension with their own version (more specific or just fixed).
